### ISSUE TITLE
uninstall option

### ISSUE THREAD

**Issue by presercomp** [jmlemetayer/abba#13]
When installed, it overrides the default opening of the index.php files within each folder.
It is necessary to uninstall, to undo the changes made by the installation and to leave the apache pages by default.

**Comment by jmlemetayer** [comment]
Hi, thanks for the feedback.

If you want to uninstall ABBA you just have to remove the installed files:

```bash
rm -rf .abba # Remove the ABBA directory, where all the SHTML, CSS and JS files are.
rm -f .htaccess # Remove the apache configuration file.
rm -f favicon.ico # If it was no replaced, remove the ABBA favicon.
```
---
Another option is to edit the apache configuration file to allow the [search for an index file](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryindex). You will have to edit the `.htaccess` file this way:

```diff
-DirectoryIndex disabled
+DirectoryIndex index.php
```
---
I am currently updating ABBA to support Bootstrap and Bootswatch v4. I will consider this uninstall option in the new version only.

**Comment by jmlemetayer** [comment]
A uninstall script has been added to the version 2.0
