### ISSUE TITLE
url problem, I cant install

### ISSUE THREAD

**Issue by mparicioitb** [jmlemetayer/abba#14]
Hi,
T=$(mktemp) && curl -sL git.io/abba -o $T && sh $T
doesnt work.
https://abba.jmldev.net/ website is down.

Thx, María.

**Comment by jmlemetayer** [comment]
I recently buy a new domain `jml.bzh` instead of `jmldev.net` but forgot to do the switch. This is now fixed!

For the next release (with bootstrap v4), I will use only the `github.io` domain to get ride of these issues.

**Comment by mparicioitb** [comment]
Really quickly, thx.
