### ISSUE TITLE
Is the project dead? "server can't find abba.jmldev.net: NXDOMAIN"

### ISSUE THREAD

**Issue by t1mothy666** [jmlemetayer/abba#15]
I can't install it because the server has no IP address anymore. Sad :(

**Comment by jmlemetayer** [comment]
Kind of ... I broke my DNS again.

But, as I have some spare time at the moment, I have started the next version using bootstrap 4. See: https://github.com/jmlemetayer/abba-next

Here is some early previews:
- http://jmlemetayer.github.io/abba-next/tests/default.html
- http://jmlemetayer.github.io/abba-next/tests/minty.html
- http://jmlemetayer.github.io/abba-next/tests/pulse.html

**Comment by jmlemetayer** [comment]
The new version 2.0 is online.

I have force all the URLs to use the `username.github.io` type (and no more the custom cname ones). As these URLs will always work.
