### ISSUE TITLE
I have problem enabling it

### ISSUE THREAD

**Issue by Gyanbu** [jmlemetayer/abba#16]
I tried to make my indexin dark mode with this and few other tools but always it looks same.
I enabled required modules but it still don't work.
![image](https://user-images.githubusercontent.com/42182265/110101496-e29ccc00-7da3-11eb-966d-bde19a63b421.png)

**Comment by jmlemetayer** [comment]
Hi,

Have you check the [Troubleshooting](https://github.com/jmlemetayer/abba#troubleshooting) ?

Do you have mod_include and mod_mime are enabled ?

**Comment by Gyanbu** [comment]
I did, I tried enabling them, I don't know which but one was already enabled

**Comment by jmlemetayer** [comment]
As you can see you have the [`[directory]` alternate text](https://github.com/jmlemetayer/abba/blob/main/abba/htaccess#L51) this means that the `.htaccess` file have been successfully loaded.

But the `.abba/html/header.shtml` file cannot be loaded (else the title will not be `Index of /Secure`).

Here are the steps I will try:

1. Check if the file exist: `=> ls`
2. Check if the file can be read by the apache user (`www-data` on ubuntu): `=> ls -l`
3. If you end up with a blank page, do the same for the css and js files.

**Comment by Gyanbu** [comment]
1. file exist
2. it can read them
3. it can read them
I runned the commands in the root directory but they didn't seem to help

**Comment by Gyanbu** [comment]
My server test directory address is [https://gyanburu.westeurope.cloudapp.azure.com/test/](url)

**Comment by jmlemetayer** [comment]
Ok seems weird ...

Do you have any apache logs which can be helpful ?

**Comment by jmlemetayer** [comment]
Another thing, as I read the word "Secure": have you done some access control configuration ?

When I tried to access the file https://gyanburu.westeurope.cloudapp.azure.com/test/.abba/css/style.css I have got a 404 error.

**Comment by jmlemetayer** [comment]
Ok. FYI the `/var/www/html/` path is a default configuration for your apache2 package.

You should be able to change this directory by modifying the apache2 configuration.
