### ISSUE TITLE
Can't install normally

### ISSUE THREAD

**Issue by MR-ZiWeiter** [jmlemetayer/abba#20]
T=$(mktemp) && curl -sL git.io/abba -o ${T} && sh ${T}
T=$(mktemp) && curl -sL github.io/abba -o ${T} && sh ${T}
The installation cannot be done successfully using this command. Is this library still being maintained?

thanks

**Comment by jmlemetayer** [comment]
Hi,

What is the result of a single `curl -sL git.io/abba` ? This should print the install script to stdout like this:

```bash
$ curl -sL git.io/abba

# GitHub production URL
BASE_URL="https://jmlemetayer.github.io/abba"

# Available themes
THEMES="cerulean:cosmo:cyborg:darkly:default:flatly:journal:litera:lumen:lux:materia:minty:morph:pulse:quartz:sandstone:simplex:sketchy:slate:solar:spacelab:superhero:united:vapor:yeti:zephyr"

# Print all available themes
print_themes()
{
        echo ${THEMES} | awk -F: '{
                for (i = 1; i <= NF; i++) {
                        printf("%2s) %s\n", i, $i);
                }
        }'
}

...
```

I have just try and it is working for me. You may have network issue.

You can try with the full github url (not the git.io shortened url):

```bash
T=$(mktemp) && curl -sL https://jmlemetayer.github.io/abba/install -o ${T} && sh ${T}
```

You can also try the `wget` command to get more informations on what is failling.

**Comment by MR-ZiWeiter** [comment]
Thank you very much! 
This seems to be OK~
Maybe our network is restricted
