### ISSUE TITLE
change asc/desc display

### ISSUE THREAD

**Issue by ThierryBesancon** [jmlemetayer/abba#22]
Hello

Thanks for ABBA that i start to use. I face a small problem. I might not be a bug in ABBA, i just don't know if it can be done with ABBA or not (and it may be related more to the autoindex module of apache2 than to ABBA).

Imagine I have a hierarchy of directories. Somewhere there is a directory "reports". It stores reports by year. So it contains subdirs like "2020", "2021", "2022". When I enter "reports" i would like the display to be descending by name (so you don't have to scroll down to the most recent things) and perhaps so again in the subdirs themselves-- whereas in the other parts of the hierarchy i want ascending display.

Any idea how this can be done ?

Thanks in advance. Best regards,
Thierry

**Comment by jmlemetayer** [comment]
Hi Thierry,

I think that what you want to achieve can be done directly by apache. Check the [IndexOrderDefault](https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html#indexorderdefault) directive.

You have 2 choices to configure it:

1. You create a `.htaccess` in your `reports` directory and configure it like that:
   ```
   IndexOrderDefault Descending Name
   ```
   This will set the descending name order by default for the `reports` directory and all its sub-directories.

2. If you want more control with the sub-directories order, I advice you not to use an `.htaccess` but to do the configuration directly in the virtual host configuration. Some thing like that:
   ```
   <VirtualHost *:80>
       DocumentRoot "/www/example2"
       ServerName www.example.org

       # Set the descending name order to the "reports" directory
       <Directory "/www/example2/reports">
           IndexOrderDefault Descending Name
      </Directory>

       # Set the ascending name order to all the "reports" sub-directories
       <Directory ~ "/www/example2/reports/.*">
           IndexOrderDefault Ascending Name
      </Directory>
   </VirtualHost>
   ```

Note that the `.htaccess` option is easier but [not recommended](https://httpd.apache.org/docs/2.4/en/howto/htaccess.html#when).

Please let me know if this solves your problem. I'll let you close this issue.

**Comment by ThierryBesancon** [comment]
Hello.

Thanks for your quick answer. Yes your solution does work and is of course fully compatible with ABBA.

 I tried the same thing before opening the issue starting from the ".htaccess" supplied with ABBA but it turns out i did some typo ("Ascending" giving "Desscending"). 

Merci encore.

I close the issue.

Thierry
